### ISSUE TITLE
Add <span> styling for replacement words

### ISSUE THREAD

**Issue by ndarville** [ndarville/djoefsk-til-dansk#5]
Just some simple CSS like:

```css
span.djoefsk {
    margin-left: 2px; margin-right: 2px;
    background-color: #CFC;
}
```

- [ ] JS
- [x] CSS

```diff
  // content.js
  function walk(rootNode) {
  // ...
      while (node = walker.nextNode()) {
          handleText(node);
      }
  }
  
  function handleText(textNode) {
      textNode.nodeValue = replaceText(textNode.nodeValue);
+   wrap(textNode, "span.djoefsk") // Pseudo code
  }
```
